name: Daily Sentiment Report          # ← shows up in the Actions tab

on:
  # ––– manual trigger from the Actions UI
  workflow_dispatch:

  # ––– automatic run every day at 04:00 UTC  (adjust cron if you like)
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-report:
    runs-on: ubuntu-latest

    # ──────────────────────────────
    # Environment variables
    # ──────────────────────────────
    env:
      # Supabase
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}

      # Mailjet
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}

      # Report sender / recipients (stored as “Org / Repo Variables”)
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      # Optional: override report date (leave blank → today)
      REPORT_DATE:           ${{ vars.REPORT_DATE }}

      # Tidy CI defaults
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1 ▸ Check out repository
      - uses: actions/checkout@v4

      # 2 ▸ Set up R (uses Posit public binary cache → faster installs)
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # (optional) Pandoc – handy for rmarkdown, but harmless if unused
      - uses: r-lib/actions/setup-pandoc@v2

      # 3 ▸ Install a real headless Chromium for pagedown
      #     browser-actions/setup-chrome v2 adds `$CHROME_PATH`
      - name: Install headless Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable
      # expose it for the R script
      - run: echo "CHROME_BIN=$CHROME_PATH" >> $GITHUB_ENV

      # 4 ▸ Linux system libraries required by popular R packages
      - name: Install Linux libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libfreetype6-dev \
            libharfbuzz-dev libfribidi-dev \
            libpng-dev libtiff5-dev libjpeg-dev

      # 5 ▸ Run the end‑to‑end script (renders, uploads, emails)
      - name: Render & send daily sentiment report
        run: Rscript run_daily_sentiment.R

      # 6 ▸ Keep artefacts (PDF/HTML) for easy inspection (optional)
      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-sentiment-artifacts
          path: |
            daily_sentiment_report.html
            daily_sentiment_report.pdf
          if-no-files-found: warn
