name: Daily Sentiment Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"          # every day @04:00 UTC

jobs:
  build-report:
    runs-on: ubuntu-latest

    env:
      # Supabase
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      # Mailjet
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      # Sender / recipients
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}
      # Optional report date override
      REPORT_DATE:           ${{ vars.REPORT_DATE }}
      # tidy‑CI defaults
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1 ▸ Checkout repo
      - uses: actions/checkout@v4

      # 2 ▸ Set up R + pandoc
      - uses: r-lib/actions/setup-r@v2
        with: { use-public-rspm: true }
      - uses: r-lib/actions/setup-pandoc@v2

      # 3 ▸ Headless Chrome for pagedown
      - name: Install headless Chrome
        id: chrome                              # ← id added
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      # 3b ▸ Export CHROME_BIN so R can pick it up
      - name: Export CHROME_BIN for R
        run: echo "CHROME_BIN=${{ steps.chrome.outputs.chrome-path }}" >> "$GITHUB_ENV"

      # 4 ▸ System libraries needed by some CRAN packages
      - name: Install Linux libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libfreetype6-dev \
            libharfbuzz-dev libfribidi-dev \
            libpng-dev libtiff5-dev libjpeg-dev

      # 5 ▸ Run the end‑to‑end R script
      - name: Render & send daily sentiment report
        run: Rscript run_daily_sentiment.R

      # 6 ▸ Upload artefacts (optional, helps debugging)
      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-sentiment-artifacts
          path: |
            daily_sentiment_report.html
            daily_sentiment_report.pdf
          if-no-files-found: warn
